import Head from "next/head";
import Image from "next/image";
import Hero from "../src/moduls/Hero";
import About from "../src/moduls/About";
import Resume from "../src/moduls/Resume";
import Portopolio from "../src/moduls/Portofolio";
import Services from "../src/moduls/Services";
import Contact from "../src/moduls/Contact";
import Skill from "../src/moduls/Skill";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico " />
            </Head>

            <Hero />
            <About />
            <Skill />
            <Resume />
            <Portopolio />
            {/* <Services /> */}
            <Contact />
        </div>
    );
}
